### ISSUE TITLE
Only layers of same output shape can be merged using sum mode. 

### ISSUE THREAD

**Issue by adriaromero** [keunwoochoi/residual_block_keras#13]
Hi there,

Thanks for your work: it's impressive to me!

But I am getting an error that I can not solve by myself.

I'm running the MNIST example and I receive this exception:

"Only layers of same output shape can be merged using sum mode. Layer shapes: [(None, 128, 32, 32), (None, 128, 32, 128)]".

I'm using theano as a backend. 

Any guess? 

Thank you.

**Comment by adriaromero** [comment]
The entire exception:

`(keras_env)`

 ```
aromero@nx2:~/work/image-classification/MIDDLE_Skin_Classification/ResNets/residual_block_keras>> THEANO_FLAGS=device=gpu,floatX=float32  srun --gres=gpu:1 --mem=10G python example.py 
==========================================
 SLURM_JOB_ID   = 53219
 SLURM_NODE     = c7
==========================================
Using Theano backend.
Using gpu device 0: GeForce GTX 980 (CNMeM is disabled, cuDNN 5103)
/imatge/aromero/keras_env/local/lib/python2.7/site-packages/theano/sandbox/cuda/__init__.py:600: UserWarning: Your cuDNN version is more recent than the one Theano officially supports. If you see any problems, try updating Theano or downgrading cuDNN to version 5.
  warnings.warn(warn)
 == MNIST ==
X_train shape: (60000, 1, 28, 28)
60000 train samples
10000 test samples
(Subtensor{int64}.0, Elemwise{add,no_inplace}.0, Elemwise{add,no_inplace}.0, Subtensor{int64}.0)
   - New residual block with
('      input shape:', (128, 32, 32))
('      kernel size:', [3, 3])
Traceback (most recent call last):
  File "example.py", line 164, in <module>
    model = get_residual_model(is_mnist=is_mnist, img_channels=img_channels, img_rows=img_rows, img_cols=img_cols)
  File "example.py", line 124, in get_residual_model
    residual_blocks = design_for_residual_blocks(num_channel_input=first_layer_channel)
  File "example.py", line 77, in design_for_residual_blocks
    kernel_sizes=image_patch_sizes[conv_idx]
  File "/work/aromero/image-classification/MIDDLE_Skin_Classification/ResNets/residual_block_keras/residual_blocks.py", line 85, in building_residual_block
    y = merge([shortcut_y, conv_y], mode='sum')
  File "/imatge/aromero/keras_env/local/lib/python2.7/site-packages/keras/engine/topology.py", line 1482, in merge
    name=name)
  File "/imatge/aromero/keras_env/local/lib/python2.7/site-packages/keras/engine/topology.py", line 1140, in __init__
    node_indices, tensor_indices)
  File "/imatge/aromero/keras_env/local/lib/python2.7/site-packages/keras/engine/topology.py", line 1175, in _arguments_validation
    'Layer shapes: %s' % input_shapes)
Exception: Only layers of same output shape can be merged using sum mode. Layer shapes: [(None, 128, 32, 32), (None, 128, 32, 128)]
srun: error: c7: task 0: Exited with exit code 1

```

**Comment by keunwoochoi** [comment]
* Is it the result of my example?
* what's image_dim_ordering and backend?

**Comment by adriaromero** [comment]
- Yes, it's the result of your "example.py" file running the MNIST case (is_mnist = True). 
- I am using th image_dim_ordering with Theano backend. Should I switch it to TF? 

Thanks!

**Comment by keunwoochoi** [comment]
I tested it on Theano and `th`, and both cifar-10 and mnist works. Keras version 1.1.1, theano 0.9.0dev4.dev-27573ab72e6307154d7bf58bfdfae68828569049. Maybe updae would help?

**Comment by adriaromero** [comment]
It helped me a lot!! I just needed to add lines `from keras import backend as K`and `K.set_image_dim_ordering('th')` on the top of the code. Thanks!!!!!

**Comment by keunwoochoi** [comment]
That makes sense, nice :)
